### ISSUE TITLE
Missing Python 3.12 build

### ISSUE THREAD

**Issue by NoAnyLove** [conda-forge/picologging-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,

It seems the build for Python 3.12 are missing, as shown in https://anaconda.org/conda-forge/picologging/files?version=0.9.3. Can someone please fix it?

Thanks

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by thewchan** [comment]
There was a CI error, the package should be available for 3.12 now. Please validate @NoAnyLove

**Comment by NoAnyLove** [comment]
It works now, thanks
